from enum import Enum
from pydantic import BaseModel

class ResumeSectionType(str, Enum):
    PERSONAL_INFORMATION = "PERSONAL_INFORMATION"
    SUMMARY = "SUMMARY"
    EXPERIENCE = "EXPERIENCE"
    PROJECTS = "PROJECTS"
    SKILLS = "SKILLS"
    EDUCATION = "EDUCATION"
    CERTIFICATIONS = "CERTIFICATIONS"
    ACHIEVEMENTS = "ACHIEVEMENTS"
    POSITIONS_OF_RESPONSIBILITY = "POSITIONS_OF_RESPONSIBILITY"
    INTERNSHIPS = "INTERNSHIPS"
    PUBLICATIONS = "PUBLICATIONS"
    RESEARCH = "RESEARCH"
    PATENTS = "PATENTS"
    CO_CURRICULAR = "CO_CURRICULAR"
    OPEN_SOURCE = "OPEN_SOURCE"
    VOLUNTEER = "VOLUNTEER"
    LANGUAGES = "LANGUAGES"
    AWARDS = "AWARDS"
    TRAINING = "TRAINING"
    WORKSHOPS = "WORKSHOPS"
    INTERESTS = "INTERESTS"
    REFERENCES = "REFERENCES"
    CUSTOM = "CUSTOM"

class ResumeSectionState(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    WAITING_FOR_USER = "WAITING_FOR_USER"

class GenericSection(BaseModel):
    title: str
    content: list[str]
