# Agent Enums
from enum import Enum

class Intent(str, Enum):
    JOB_SEARCH = "JOB_SEARCH"
    GENERAL_CHAT = "GENERAL_CHAT"
    FOLLOW_UP = "FOLLOW_UP"
    RESUME_TAILORING = "RESUME_TAILORING"
    INTERVIEW_PREPARATION = "INTERVIEW_PREPARATION"
    UNKNOWN = "UNKNOWN"
