"""initial

Revision ID: 152f26a96c53
Revises: 
Create Date: 2026-07-07 16:16:18.855595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '152f26a96c53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_hash', sa.String(), nullable=False),
    sa.Column('processing_status', sa.Enum('RAW', 'GENERATING', 'READY', 'FAILED', name='jobknowledgestatus'), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('education_requirements', sa.String(), nullable=True),
    sa.Column('salary_information', sa.String(), nullable=True),
    sa.Column('primary_domain', sa.Enum('SOFTWARE_ENGINEERING', 'AI_MACHINE_LEARNING', 'DATA_SCIENCE', 'CYBER_SECURITY', 'CLOUD_COMPUTING', 'DEVOPS', 'MECHANICAL_ENGINEERING', 'CIVIL_ENGINEERING', 'CHEMICAL_ENGINEERING', 'ELECTRICAL_ENGINEERING', 'ELECTRONICS_ENGINEERING', 'EMBEDDED_SYSTEMS', 'UNKNOWN_ENGINEERING_DOMAIN', name='engineeringdomain'), nullable=False),
    sa.Column('secondary_domains', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('must_have_requirements', sa.JSON(), nullable=True),
    sa.Column('preferred_requirements', sa.JSON(), nullable=True),
    sa.Column('bonus_requirements', sa.JSON(), nullable=True),
    sa.Column('semantic_summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_knowledge_job_hash'), 'job_knowledge', ['job_hash'], unique=True)
    op.create_table('market_intelligence_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('market_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_intelligence_cache_last_refreshed'), 'market_intelligence_cache', ['last_refreshed'], unique=False)
    op.create_index(op.f('ix_market_intelligence_cache_role_name'), 'market_intelligence_cache', ['role_name'], unique=True)
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('CANDIDATE_KNOWLEDGE', name='artifacttype'), nullable=False),
    sa.Column('artifact_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'STALE', name='insightstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_insights_artifact_type'), 'candidate_insights', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_candidate_insights_candidate_profile_id'), 'candidate_insights', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_insights_status'), 'candidate_insights', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('active_workspace_id', sa.UUID(), nullable=True),
    sa.Column('conversation_type', sa.Enum('JOB_SEARCH', 'GENERAL_CHAT', 'RESUME_TAILORING', 'INTERVIEW_PREPARATION', 'COMPANY_ANALYSIS', name='conversationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='conversationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_workspace_id'], ['search_workspaces.id'], name='fk_active_workspace', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='role'), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'JOB_RESULTS', 'SYSTEM_EVENT', 'TOOL_RESULT', 'ERROR', name='messagetype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('original_query', sa.String(), nullable=False),
    sa.Column('normalized_query', sa.String(), nullable=True),
    sa.Column('optimized_query', sa.String(), nullable=True),
    sa.Column('search_provider', sa.String(), nullable=False),
    sa.Column('total_jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('jobs_requested', sa.Integer(), nullable=False),
    sa.Column('jobs_received', sa.Integer(), nullable=False),
    sa.Column('jobs_persisted', sa.Integer(), nullable=False),
    sa.Column('failed_jobs', sa.Integer(), nullable=False),
    sa.Column('processing_duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.Enum('CREATED', 'FETCHING', 'RAW_JOBS_READY', 'KNOWLEDGE_GENERATING', 'EMBEDDING', 'MATCHING', 'EXPLAINING', 'READY', 'FAILED', 'EXPIRED', name='processingstatus'), nullable=False),
    sa.Column('search_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_workspaces_candidate_profile_id'), 'search_workspaces', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_search_workspaces_conversation_id'), 'search_workspaces', ['conversation_id'], unique=False)
    op.create_table('job_search_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_knowledge_id', sa.UUID(), nullable=True),
    sa.Column('provider_job_id', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('raw_job_json', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.Enum('RAW', 'PROCESSING', 'KNOWLEDGE_GENERATED', 'EMBEDDED', 'MATCHED', 'FAILED', name='jobprocessingstatus'), nullable=False),
    sa.Column('knowledge_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('deterministic_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_knowledge_id'], ['job_knowledge.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['search_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_search_results_job_knowledge_id'), 'job_search_results', ['job_knowledge_id'], unique=False)
    op.create_index(op.f('ix_job_search_results_workspace_id'), 'job_search_results', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_search_results_workspace_id'), table_name='job_search_results')
    op.drop_index(op.f('ix_job_search_results_job_knowledge_id'), table_name='job_search_results')
    op.drop_table('job_search_results')
    op.drop_index(op.f('ix_search_workspaces_conversation_id'), table_name='search_workspaces')
    op.drop_index(op.f('ix_search_workspaces_candidate_profile_id'), table_name='search_workspaces')
    op.drop_table('search_workspaces')
    op.drop_table('conversation_messages')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_candidate_insights_status'), table_name='candidate_insights')
    op.drop_index(op.f('ix_candidate_insights_candidate_profile_id'), table_name='candidate_insights')
    op.drop_index(op.f('ix_candidate_insights_artifact_type'), table_name='candidate_insights')
    op.drop_table('candidate_insights')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_market_intelligence_cache_role_name'), table_name='market_intelligence_cache')
    op.drop_index(op.f('ix_market_intelligence_cache_last_refreshed'), table_name='market_intelligence_cache')
    op.drop_table('market_intelligence_cache')
    op.drop_index(op.f('ix_job_knowledge_job_hash'), table_name='job_knowledge')
    op.drop_table('job_knowledge')
    # ### end Alembic commands ###
