"""add_chat_persistence_models

Revision ID: 1db080c94289
Revises: 644b70389be2
Create Date: 2026-06-23 22:57:44.533739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db080c94289'
down_revision: Union[str, Sequence[str], None] = '644b70389be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chats_active_job_pool_id'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'active_filters')
    op.drop_column('chats', 'active_job_pool_id')
    op.drop_column('chats', 'selected_job_id')
    op.add_column('job_pools', sa.Column('insights_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('job_pools', 'active_insights')
    op.drop_column('job_pools', 'original_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_pools', sa.Column('original_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('job_pools', sa.Column('active_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('job_pools', 'insights_cache')
    op.add_column('chats', sa.Column('selected_job_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('active_job_pool_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('active_filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_chats_active_job_pool_id'), 'chats', 'job_pools', ['active_job_pool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
