"""remove job search models

Revision ID: 21d2fb04a41f
Revises: b3b341136b5a
Create Date: 2026-07-18 19:30:54.811213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21d2fb04a41f'
down_revision: Union[str, Sequence[str], None] = 'b3b341136b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_intelligence_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('market_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_intelligence_cache_last_refreshed'), 'market_intelligence_cache', ['last_refreshed'], unique=False)
    op.create_index(op.f('ix_market_intelligence_cache_role_name'), 'market_intelligence_cache', ['role_name'], unique=True)
    op.drop_index(op.f('ix_job_search_results_job_knowledge_id'), table_name='job_search_results')
    op.drop_index(op.f('ix_job_search_results_workspace_id'), table_name='job_search_results')
    op.drop_table('job_search_results')
    op.drop_index(op.f('ix_job_knowledge_job_hash'), table_name='job_knowledge')
    op.drop_table('job_knowledge')
    op.drop_constraint(op.f('fk_active_workspace'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'active_workspace_id')
    op.drop_index(op.f('ix_search_workspaces_candidate_profile_id'), table_name='search_workspaces')
    op.drop_index(op.f('ix_search_workspaces_conversation_id'), table_name='search_workspaces')
    op.drop_table('search_workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('active_workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_active_workspace'), 'conversations', 'search_workspaces', ['active_workspace_id'], ['id'], ondelete='SET NULL')
    op.create_table('search_workspaces',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('normalized_query', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('optimized_query', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('search_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_jobs_fetched', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobs_requested', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobs_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobs_persisted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('processing_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processing_status', postgresql.ENUM('CREATED', 'FETCHING', 'RAW_JOBS_READY', 'KNOWLEDGE_GENERATING', 'EMBEDDING', 'MATCHING', 'EXPLAINING', 'READY', 'FAILED', 'EXPIRED', name='processingstatus'), autoincrement=False, nullable=False),
    sa.Column('search_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('search_workspaces_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('search_workspaces_pkey'))
    )
    op.create_index(op.f('ix_search_workspaces_conversation_id'), 'search_workspaces', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_search_workspaces_candidate_profile_id'), 'search_workspaces', ['candidate_profile_id'], unique=False)
    op.create_table('job_search_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_knowledge_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apply_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_job_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processing_status', postgresql.ENUM('RAW', 'PROCESSING', 'KNOWLEDGE_GENERATED', 'EMBEDDED', 'MATCHED', 'FAILED', name='jobprocessingstatus'), autoincrement=False, nullable=False),
    sa.Column('knowledge_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('embedding_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('semantic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deterministic_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('matching_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comparison_evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_explanation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_knowledge_id'], ['job_knowledge.id'], name=op.f('job_search_results_job_knowledge_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['search_workspaces.id'], name=op.f('job_search_results_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_search_results_pkey'))
    )
    op.create_index(op.f('ix_job_search_results_workspace_id'), 'job_search_results', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_job_search_results_job_knowledge_id'), 'job_search_results', ['job_knowledge_id'], unique=False)
    op.create_table('job_knowledge',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processing_status', postgresql.ENUM('RAW', 'GENERATING', 'READY', 'FAILED', name='jobknowledgestatus'), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary_information', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('minimum_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employment_level', postgresql.ENUM('INTERN', 'FRESHER', 'JUNIOR', 'MID', 'SENIOR', 'LEAD', 'STAFF', 'PRINCIPAL', name='employmentlevel'), autoincrement=False, nullable=True),
    sa.Column('required_degrees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_degrees', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('required_specializations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_specializations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('primary_domain', postgresql.ENUM('SOFTWARE_ENGINEERING', 'AI_MACHINE_LEARNING', 'DATA_SCIENCE', 'CYBER_SECURITY', 'CLOUD_COMPUTING', 'DEVOPS', 'MECHANICAL_ENGINEERING', 'CIVIL_ENGINEERING', 'CHEMICAL_ENGINEERING', 'ELECTRICAL_ENGINEERING', 'ELECTRONICS_ENGINEERING', 'EMBEDDED_SYSTEMS', 'UNKNOWN_ENGINEERING_DOMAIN', name='engineeringdomain'), autoincrement=False, nullable=False),
    sa.Column('secondary_domains', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('required_technologies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_technologies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('required_capabilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_capabilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('required_certifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_certifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('responsibilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('benefits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('job_knowledge_pkey'))
    )
    op.create_index(op.f('ix_job_knowledge_job_hash'), 'job_knowledge', ['job_hash'], unique=True)
    op.drop_index(op.f('ix_market_intelligence_cache_role_name'), table_name='market_intelligence_cache')
    op.drop_index(op.f('ix_market_intelligence_cache_last_refreshed'), table_name='market_intelligence_cache')
    op.drop_table('market_intelligence_cache')
    # ### end Alembic commands ###
