"""Add raw_knowledge to JobKnowledge

Revision ID: 2646abcf47a1
Revises: decb1021e8ba
Create Date: 2026-07-20 13:36:24.816576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2646abcf47a1'
down_revision: Union[str, Sequence[str], None] = 'decb1021e8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_knowledge', sa.Column('raw_knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_knowledge', 'raw_knowledge')
    # ### end Alembic commands ###
