"""Refactor CandidateInsights to AI Artifact store

Revision ID: 9d5c9d62371b
Revises: 1db080c94289
Create Date: 2026-06-26 00:52:21.650289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d5c9d62371b'
down_revision: Union[str, Sequence[str], None] = '1db080c94289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    artifact_type_enum = sa.Enum('CANDIDATE_KNOWLEDGE', name='artifacttype')
    artifact_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('candidate_insights', sa.Column('artifact_type', artifact_type_enum, server_default='CANDIDATE_KNOWLEDGE', nullable=False))
    op.add_column('candidate_insights', sa.Column('artifact_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('candidate_insights', sa.Column('engine_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_candidate_insights_artifact_type'), 'candidate_insights', ['artifact_type'], unique=False)
    op.drop_column('candidate_insights', 'insights_json')
    op.drop_column('candidate_insights', 'graph_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_insights', sa.Column('graph_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_insights', sa.Column('insights_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_candidate_insights_artifact_type'), table_name='candidate_insights')
    op.drop_column('candidate_insights', 'engine_version')
    op.drop_column('candidate_insights', 'artifact_json')
    op.drop_column('candidate_insights', 'artifact_type')
    
    artifact_type_enum = sa.Enum('CANDIDATE_KNOWLEDGE', name='artifacttype')
    artifact_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
