"""add job search agent models

Revision ID: decb1021e8ba
Revises: 21d2fb04a41f
Create Date: 2026-07-20 09:53:23.886650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'decb1021e8ba'
down_revision: Union[str, Sequence[str], None] = '21d2fb04a41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('required_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Enum('RAW', 'EXTRACTED', 'FAILED', name='jobknowledgestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_knowledge_job_hash'), 'job_knowledge', ['job_hash'], unique=True)
    op.create_table('job_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('original_query', sa.String(), nullable=False),
    sa.Column('optimized_role', sa.String(), nullable=True),
    sa.Column('optimized_location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='searchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_searches_candidate_profile_id'), 'job_searches', ['candidate_profile_id'], unique=False)
    op.create_table('job_match_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_search_id', sa.UUID(), nullable=False),
    sa.Column('job_knowledge_id', sa.UUID(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('deterministic_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('matching_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_knowledge_id'], ['job_knowledge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_search_id'], ['job_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_scores_job_knowledge_id'), 'job_match_scores', ['job_knowledge_id'], unique=False)
    op.create_index(op.f('ix_job_match_scores_job_search_id'), 'job_match_scores', ['job_search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_match_scores_job_search_id'), table_name='job_match_scores')
    op.drop_index(op.f('ix_job_match_scores_job_knowledge_id'), table_name='job_match_scores')
    op.drop_table('job_match_scores')
    op.drop_index(op.f('ix_job_searches_candidate_profile_id'), table_name='job_searches')
    op.drop_table('job_searches')
    op.drop_index(op.f('ix_job_knowledge_job_hash'), table_name='job_knowledge')
    op.drop_table('job_knowledge')
    # ### end Alembic commands ###
