"""Add CandidateInsights and MarketIntelligenceCache models

Revision ID: f4ad061ed9c0
Revises: 0315a23c5761
Create Date: 2026-06-18 13:26:53.621921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4ad061ed9c0'
down_revision: Union[str, Sequence[str], None] = '0315a23c5761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_intelligence_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('market_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_intelligence_cache_last_refreshed'), 'market_intelligence_cache', ['last_refreshed'], unique=False)
    op.create_index(op.f('ix_market_intelligence_cache_role_name'), 'market_intelligence_cache', ['role_name'], unique=True)
    op.create_table('candidate_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('insights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graph_version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'STALE', name='insightstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_insights_candidate_profile_id'), 'candidate_insights', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_insights_status'), 'candidate_insights', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_insights_status'), table_name='candidate_insights')
    op.drop_index(op.f('ix_candidate_insights_candidate_profile_id'), table_name='candidate_insights')
    op.drop_table('candidate_insights')
    op.drop_index(op.f('ix_market_intelligence_cache_role_name'), table_name='market_intelligence_cache')
    op.drop_index(op.f('ix_market_intelligence_cache_last_refreshed'), table_name='market_intelligence_cache')
    op.drop_table('market_intelligence_cache')
    # ### end Alembic commands ###
